on: [push]
name: build
jobs:
  stack:
    name: not-a-connect4
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-haskell@v1.1
        with:
          #ghc-version: '8.10.4' # Exact version of ghc to use
          enable-stack: true
            #stack-version: 'lts-18.1'
      - run: stack test
