on: [push, pull_request]
jobs:
  stack:
    name: test not-a-connect4 using nix
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-haskell@v1.1
        with:
          #ghc-version: '8.10.4' 
          enable-stack: true
          stack-version: 'latest'
      - run: stack test 
