on: [push, pull_request]
jobs:
  stack:
    name: test not-a-connect4 using stack
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-haskell@v1.1
        with:
          ghc-version: '8.8.1' # Exact version of ghc to use
          enable-stack: true
          stack-version: 'latest'
      - run: stack test 
