on: [push]
name: build
jobs:
  stack:
    name: test not-a-connect4 using stack
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-haskell@v1.1
        with:
          ghc-version: '8.10.4' 
          enable-stack: true
          stack-version: '18.1'
      - run: stack test 
